### ISSUE TITLE
make more broadly applicable

### ISSUE THREAD

**Issue by afeld** [18F/technology-budgeting#18]
Reading through the handbook, it struck me that very little of it was actually specific to states. Seems that it could be made applicable to federal government as well (at least), mostly with find-and-replace:

- Governor -> Executive
- Legislature -> Lawmakers
- Etc.

Thoughts?

**Comment by waldoj** [comment]
Well, we don't actually know if that's the case. :) It would be dangerous to provide advice that was convincing-looking and wrong — we'd need to root proposals in solid research. There is good cause to believe that the methods of working with state legislatures that we prescribe here simply don't work with congress...but that they _would_ work with agency-level budget officials acting in in a role similar to that played by legislators.

That said, the work is underway! @vickimcfadden and @MCHopson are conducting the necessary research right now, as phase 3 of this 10x project, interviewing stakeholders in a variety of federal agencies. Their output will be specific proposals for how to amend this handbook so that it can apply to the federal government. They'll likely wrap that work up in a few weeks.

**Comment by chuckgeorgo** [comment]
as someone who has worked with hundreds of state, local and municipal agencies, and minding the view that "perfect is enemy of the good",  I'd offer that it would not take any agency much effort to scrape many sections of the handbook to admire for their own 18F-like efforts.

**Comment by waldoj** [comment]
That would be so great to see! Anybody is welcome to take this text and do anything they like with it — it's all public domain. No doubt any of the agencies you cite would well know how their own organization works in terms of budgeting processes, and would be well equipped to turn this into something that works for them.

**Comment by afeld** [comment]
Done! https://derisking-guide.18f.gov/
